name: CI
on:
  workflow_dispatch:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-11
          - windows-2022
        node_version:
          - 16
        node_arch:
          - x64
        include:
          - os: windows-2022
            node_version: 16
            node_arch: x86
          # - os: macos-11
          #   node_version: 18
          #   node_arch: arm64
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - name: Install Dependencies and Build
        run: npm install

      - name: Prebuildify x64
        if: ${{ contains(matrix.node_arch, 'x64') }}
        run: npm run prebuildify

      - name: Prebuildify x86
        if: ${{ contains(matrix.node_arch, 'x86') }}
        run: npm run prebuildify-ia32

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./prebuilds
